# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3adeec31115badaba7695c1f05bf683b1106059757f88c743ef3fb738cbf2638582856830b68089797da53b86203f982c1f81ec958e385f7d82602aa99c30b06

test:
  secret_key_base: f4a3dede966a13b9f31932575b8ef60e2d42ec5394517a79d92d55f94831c3a4dd0bee33dd8cc7f0a73781999b4b9d1ba2c464ae6fd522aff851890ab62b3268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>